# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='overview',
            field=models.TextField(blank=True),
        ),
    ]
