# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 22:38
from __future__ import unicode_literals

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_content_file_image_text_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='content',
            name='order',
            field=course.fields.OrderField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='module',
            name='order',
            field=course.fields.OrderField(blank=True, null=True),
        ),
    ]
