# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 22:41
from __future__ import unicode_literals

import course.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20170805_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='order',
            field=course.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='order',
            field=course.fields.OrderField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
